### PR TITLE
Update release build action

### PR DESCRIPTION
**Pull request by larsnaesbye**
Updates the (currently) unused build action as the first part of an attempt to revitalize them

### CODE REVIEW

**Comment by gwbres** [comment]
Hello @larsnaesbye 

Thank you for your contribution, yep definitely need to put the release back to life

**Review by gwbres — APPROVED** [review]

**Comment by larsnaesbye** [comment]
@gwbres  - I was thinking of making test releases on my fork as they should not contaminate the official repository?

**Comment by larsnaesbye** [comment]
Hmm, it seems I cannot do that because one cannot create tags on forked repos. I will find another way....

**Comment by gwbres** [comment]
Well.. that's too bad because that would have been fairly easy...

**Comment by larsnaesbye** [comment]
Maybe I will just upload a copy to another repo and experiment from there.

**Comment by gwbres** [comment]
> Maybe I will just upload a copy to another repo and experiment from there.

We'll have more release soon, we can fix that soon.
Do you have a little time to review my QC improvements ?

**Comment by gwbres** [comment]
1. x86_64-unknown-linux-musl complains the linker flag -lz does not exist
2. x86_64-apple-darwin did pass, but it complains it cannot create a directory that already exists.
Looks like a faulty script or faulty docker environment
3. x86_64-pc-windows-gnu did pass but it failed to publish to the server due to some credentials issues.
Faulty docker environment, or faulty process once again. This error might have induced (2) ?
image

**Comment by larsnaesbye** [comment]
@gwbres Im hoping for this: https://github.com/houseabsolute/actions-rust-cross/pull/7 to be resolved and maybe use this action instead...

**Comment by gwbres** [comment]
It's already available, under his own name https://github.com/aaronvg/actions-rust-cross 
We don't necessarily have to wait

**Comment by larsnaesbye** [comment]
Sure! I may be looking at it tomorrow :)

**Comment by larsnaesbye** [comment]
It got merged, so we can use the original repo now

**Pull request merged**
