### PR TITLE
Improve support for BDRC ephemeris

### PR DESCRIPTION
**Pull request by FlowLoveV**
-  Fix bugs in kepler orbit calculation.Correct calculation of GPS,BDS,GALIEO satellite position and velocity is now supported on all versions of rinex.QZSS support has not been tested.
- The next step is to refer to rtklib and update the satellite ephemeris calculations for GLONASS and SBAS to get their exact positions instead of the approximate positions reported.
-  Corrected BDS ephemeris update time to one hour

### CODE REVIEW

**Comment by gwbres** [comment]
@FlowLoveV,

this is an amazing contribution, thank you so much!
 
Lately, I'm been working on the `sbas` branch and was able to myself slightly improve this portion of the library (i'm getting my first SBAS results, and mostly correct BDS results). But with this contribution, it should be close to perfection.

We have initiated [this topic](https://github.com/orgs/nyx-space/discussions/310) to discuss how Nyx-space could answer the need to resolve orbital attitudes from keplerian parameters.  

I propose this plan:
 
  - I'm testing your proposal the next few days, see how much better we perform in keplerian navigation and we most likely merge a combination of this proposal (75%) and my pending work (25%)
  -  I'm leaning towards eventually getting rid of `kepler2position` and `kepler2velocity`, by means of being able to form a `Nyx::Orbit` object. So we rely on external core calculations and reduce RINEX. What is your take on this ?
  - Right now is not the good time to do that, due to heavy work in the Hifitime/Nyx/Anise ecosystem. 
  So it's perfectly ok to continue improve our core features, and will eventually treat them different, in the long term

**Comment by gwbres** [comment]
> The next step is to refer to rtklib and update the satellite ephemeris calculations for GLONASS and SBAS to get their exact positions instead of the approximate positions reported.

Yes, exactly. My plan is the following

- conclude standard constellation 1D navigation. We mostly need to conclude BDS, this branch will most likely enable it. Ideally confirm QZSS and IRNSS as well.
- then proceed to SBAS: confirm it works as well. It will require a slight rework of the RINEX-Cli orbital object
- then confirm Glonass

**Comment by FlowLoveV** [comment]
According to what I have learned, broadcast ephemeris predicts orbits in two main ways:
1. Use Kepler orbital elements to describe orbits, such as GPS, BDS, GALIEO, QZSS
2. Use numerical integration to calculate orbits, such as GLONASS, SBAS

In the first way, the relativistic correction of satellite clock errors depends on Kepler orbital parameters ($E_k$), I am not sure whether the Nyx library can perfectly meet our needs (if it can, that would be great)

**Comment by gwbres** [comment]
@FlowLoveV, @larsnaesbye,

I can already confirm that this contribution finalizes the work for BeiDou.
This is what I get when surveying the Esbjerg (DNK) station using only radio messages from BeiDou (real time brdc)

My latest/best branch: x_err=5m, y_err=28cm, z_err=37m

beidou_prev

This branch: x_err=2.5m, y_err=1.17m, z_err=4m

beidou_new

**Review by gwbres — APPROVED** [review]

**Pull request merged**
