### PR TITLE
RINEX v2 ionosphere parameter parsing

### PR DESCRIPTION
**Pull request by fedosgad**

### CODE REVIEW

**Comment by gwbres** [comment]
Almost done back porting the previous PR, will conclude this either tonight or tomorrow

**Comment by gwbres** [comment]
- Also fix incapability to store several models (one per constellation) in RINEX3.
This PR adds support for all RINEX2/3 constellations
- Add more examples and improve API documentations
- Add more tests

**Review by gwbres — APPROVED** [review]

**Comment by gwbres** [comment]
Thank you for your contribution, this will be added to V0.16 that I'm publishing this week end

**Comment by fedosgad** [comment]
Thanks for your time on this PR too!

**Pull request merged**
