### PR TITLE
carrier signal: improve signal identification

### PR DESCRIPTION
**Pull request by gwbres**
- fix a few missing cases when identifying frequency bands in ATX records parsing
- the carrier.rs structures was vastly improved "recently", it looks like the ATX topic got left behind
-  #103

### CODE REVIEW

**Comment by lnicola** [comment]
Sorry, I'd have to learn much more about RINEX to meaningfully say that this is fine. But I think it matches the change in the other PR.

**Comment by gwbres** [comment]
Hello @lnicola,
safe merge. It only impacts this exotic format, and we"re fixing minor issues

**Comment by lnicola** [comment]
I know. Feel free to merge 😀.

**Comment by gwbres** [comment]
> I know. Feel free to merge 😀.

I can no longer merge without approvals

**Review by lnicola — APPROVED** [review]

**Comment by gwbres** [comment]
> > I know. Feel free to merge 😀.
> 
> I can no longer merge without approvals

I leave the issue open, see if people that actually use ATX (not my case) see an improvement

**Comment by lnicola** [comment]
> I can no longer merge without approvals

It might not be in the spirit of that restriction, but can you self-approve? I forgot if that counts.

**Pull request merged**
