### PR TITLE
WIP: Guide for people switching from `teqc`

### PR DESCRIPTION
**Pull request by larsnaesbye**
A helping document for those who come from `teqc` to help adoption of `rinex-cli`.

### CODE REVIEW

**Comment by gwbres** [comment]
Hello @larsnaesbye, 

FYI I reworked the CI scripts based on other Rust repos that I have found, this will probably fix the "autobuilder" issues.  
This will be merged in the next release

**Comment by larsnaesbye** [comment]
Perfect. I will remove that text from this guide then.

**Comment by gwbres** [comment]
> Perfect. I will remove that text from this guide then.

👍 let's wait until the next release though, so we make sure it does work fine.
I should give the "pre release" option a try next time

**Comment by gwbres** [comment]
Hello @larsnaesbye,

I started a Wiki for this project, which is probably the best way to exhibit real world applications.  
I translated what you did into a TEQC category, are you fine with continuing this work in the Wiki pages ?
Let me know if you can correctly access the RINEX edition interface

**Comment by larsnaesbye** [comment]
Sure! I can now direct my former colleagues to this :-)

**Comment by larsnaesbye** [comment]
Maybe we need a link to the Wiki from the main README, though.

**Comment by gwbres** [comment]
Sure, this in the pipe in the `Develop` branch, I'm not sure when I'll proceed to the next release, there are still a couple of things that I'd like to wrap up. We also should take advantage of the next release to try the new "auto builder" approach

**Pull request closed without merging**
