### PR TITLE
rinex crate: update to georust infrastructure

### PR DESCRIPTION
**Pull request by gwbres**
This library and associated toolkits were integrated into the georust community. 

Update all URL and crates io interfacing

### CODE REVIEW

**Comment by gwbres** [comment]
@larsnaesbye, @lnicola, @rmanoka 

Testing a crates i/o publication, since i will have to publish new crates features and fixes in a very near future

following up on : https://github.com/georust/geo/issues/1016

**Comment by gwbres** [comment]
Nothing to report, everything went smooth. All URL in official documentation have been updated.

This raised a [new issue](https://github.com/georust/rinex/issues/106) that will need to be addressed separetly

**Review by lnicola — APPROVED** [review]
No strong opinion, but we might also want to update the `science` category to `science::geo`.

**Comment by gwbres** [comment]
> No strong opinion, but we might also want to update the `science` category to `science::geo`.

is it possible to have both? or it's only either one, because this tool is more than geo, it's also about signal processing

**Comment by lnicola** [comment]
It's [here](https://crates.io/category_slugs), but fair enough, let's not change it :-).

**Comment by gwbres** [comment]
> It's [here](https://crates.io/category_slugs), but fair enough, let's not change it :-).

cool thanks for pointing that out. They were introduced since last time I checked. I stacked this new category

**Pull request merged**
